/**
 * Sync UI: reads contract-addresses.json and deployments/<network>/, writes
 * contract-addresses.generated.ts, ABI files, and subgraph networks to output/sync-ui/.
 * User must manually copy the contents of output/sync-ui/ into the UI repo's src/
 * and merge subgraph-networks.json into the subgraph repo's networks.json.
 */

import * as fs from 'fs';
import * as path from 'path';
import { ethers } from 'ethers';

const CONTRACTS_ROOT = path.join(__dirname, '..');
const OUTPUT_ROOT = path.join(CONTRACTS_ROOT, 'output', 'sync-ui');
const CONTRACT_ADDRESSES_PATH = path.join(CONTRACTS_ROOT, 'contract-addresses.json');
const DEPLOYMENTS_DIR = path.join(CONTRACTS_ROOT, 'deployments');

const NETWORK_CHAIN_IDS: Record<string, number> = {
  localhost: 31337,
  sepolia: 11155111,
  mainnet: 1,
};

interface ContractEntry {
  address: string;
  implementation?: string;
}

type ContractAddressesJson = Record<string, Record<string, ContractEntry>>;

/** Subgraph networks.json fragment: network -> dataSourceName -> { address, startBlock? }. */
type SubgraphNetworksOutput = Record<string, Record<string, { address: string; startBlock?: number }>>;

interface UIContractAddresses {
  inheritance: string | null;
  forwarding: string | null;
  forwardingEOA: string | null;
  legacyAgreement: string | null;
  premiumSetting: string | null;
  premiumRegistry: string | null;
  timeLockERC20: string | null;
  timeLockERC721: string | null;
  timeLockERC1155: string | null;
  timeLock: string | null;
  timelockRouter: string | null;
  usdcAddress: string | null;
  usdtAddress: string | null;
  tokenWhitelist: string | null;
}

const CONTRACT_TO_UI_KEY: Record<string, keyof UIContractAddresses> = {
  MultisigLegacyRouter: 'inheritance',
  TransferLegacyRouter: 'forwarding',
  TransferEOALegacyRouter: 'forwardingEOA',
  EIP712LegacyVerifier: 'legacyAgreement',
  PremiumSetting: 'premiumSetting',
  PremiumRegistry: 'premiumRegistry',
  TimelockERC20: 'timeLockERC20',
  TimelockERC721: 'timeLockERC721',
  TimelockERC1155: 'timeLockERC1155',
  TimeLockRouter: 'timeLock',
  ERC20Token_USDC: 'usdcAddress',
  ERC20Token_USDT: 'usdtAddress',
  TokenWhiteList: 'tokenWhitelist',
};

function checksum(addr: string | undefined): string | null {
  if (!addr || typeof addr !== 'string') return null;
  try {
    return ethers.utils.getAddress(addr);
  } catch {
    return null;
  }
}

function buildUIContractAddresses(networkContracts: Record<string, ContractEntry>): UIContractAddresses {
  const out: UIContractAddresses = {
    inheritance: null,
    forwarding: null,
    forwardingEOA: null,
    legacyAgreement: null,
    premiumSetting: null,
    premiumRegistry: null,
    timeLockERC20: null,
    timeLockERC721: null,
    timeLockERC1155: null,
    timeLock: null,
    timelockRouter: null,
    usdcAddress: null,
    usdtAddress: null,
    tokenWhitelist: null,
  };
  for (const [contractName, key] of Object.entries(CONTRACT_TO_UI_KEY)) {
    const entry = networkContracts[contractName];
    if (entry?.address) {
      const addr = checksum(entry.address);
      if (addr) out[key] = addr;
    }
  }
  if (out.timeLock) out.timelockRouter = out.timeLock;
  return out;
}

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function getStartBlock(network: string, contractName: string): number | undefined {
  const deploymentsNetwork = path.join(DEPLOYMENTS_DIR, network);
  for (const artifactName of [`${contractName}.json`, `${contractName}_Proxy.json`]) {
    const artifactPath = path.join(deploymentsNetwork, artifactName);
    if (!fs.existsSync(artifactPath)) continue;
    try {
      const content = fs.readFileSync(artifactPath, 'utf-8');
      const parsed = JSON.parse(content) as { receipt?: { blockNumber?: number } };
      const block = parsed.receipt?.blockNumber;
      if (typeof block === 'number') return block;
    } catch {
      // ignore
    }
  }
  return undefined;
}

function writeAddresses(): void {
  const data = fs.readFileSync(CONTRACT_ADDRESSES_PATH, 'utf-8');
  const parsed = JSON.parse(data) as ContractAddressesJson;

  const lines: string[] = [
    '// Generated by scripts/sync-ui.ts — do not edit by hand.',
    '// Copy this file (and sibling dirs) into the UI repo src/ after running npm run sync-ui.',
    '',
    'export type ContractAddressesByChainId = Record<number, {',
    '  inheritance: string | null;',
    '  forwarding: string | null;',
    '  forwardingEOA: string | null;',
    '  legacyAgreement: string | null;',
    '  premiumSetting: string | null;',
    '  premiumRegistry: string | null;',
    '  timeLockERC20: string | null;',
    '  timeLockERC721: string | null;',
    '  timeLockERC1155: string | null;',
    '  timeLock: string | null;',
    '  timelockRouter: string | null;',
    '  usdcAddress: string | null;',
    '  usdtAddress: string | null;',
    '  tokenWhitelist: string | null;',
    '}>;',
    '',
    'export const CONTRACT_ADDRESSES_BY_CHAIN_ID: ContractAddressesByChainId = {',
  ];

  const seenChainIds = new Set<number>();
  if (parsed.hardhat && !parsed.localhost) {
    parsed.localhost = parsed.hardhat;
  }
  for (const [network, chainId] of Object.entries(NETWORK_CHAIN_IDS)) {
    if (seenChainIds.has(chainId)) continue;
    const networkContracts = parsed[network];
    if (!networkContracts) continue;
    seenChainIds.add(chainId);
    const addrs = buildUIContractAddresses(networkContracts);
    lines.push(`  ${chainId}: {`);
    for (const [k, v] of Object.entries(addrs)) {
      const val = v === null ? 'null' : `'${v}'`;
      lines.push(`    ${k}: ${val},`);
    }
    if (addrs.timelockRouter === null && addrs.timeLock) {
      lines.push(`    timelockRouter: '${addrs.timeLock}',`);
    }
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  const outPath = path.join(OUTPUT_ROOT, 'configs', 'contract-addresses.generated.ts');
  ensureDir(path.dirname(outPath));
  fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
  console.log('Wrote', path.relative(CONTRACTS_ROOT, outPath));
}

/** Admin UI only needs a subset of contracts per chain (computing-admin). */
const ADMIN_CONTRACT_MAP: Record<string, 'premiumRegistry' | 'payment' | 'configBanner' | 'tokenWhiteList'> = {
  PremiumRegistry: 'premiumRegistry',
  Payment: 'payment',
  Banner: 'configBanner',
  TokenWhiteList: 'tokenWhiteList',
};

function buildAdminContractAddresses(
  networkContracts: Record<string, ContractEntry>
): Record<'premiumRegistry' | 'payment' | 'configBanner' | 'tokenWhiteList', string | null> {
  const out: Record<'premiumRegistry' | 'payment' | 'configBanner' | 'tokenWhiteList', string | null> = {
    premiumRegistry: null,
    payment: null,
    configBanner: null,
    tokenWhiteList: null,
  };
  for (const [contractName, key] of Object.entries(ADMIN_CONTRACT_MAP)) {
    const entry = networkContracts[contractName];
    if (entry?.address) {
      const addr = checksum(entry.address);
      if (addr) out[key] = addr;
    }
  }
  return out;
}

function writeAdminAddresses(): void {
  const data = fs.readFileSync(CONTRACT_ADDRESSES_PATH, 'utf-8');
  const parsed = JSON.parse(data) as ContractAddressesJson;

  const lines: string[] = [
    '// Generated by scripts/sync-ui.ts — do not edit by hand.',
    '// Copy this file to computing-admin/src/configs/contract-addresses.generated.ts',
    '// (replace the existing file there).',
    '',
    'export type AdminContractAddressesByChainId = Record<number, {',
    '  premiumRegistry: string | null;',
    '  payment: string | null;',
    '  configBanner: string | null;',
    '  tokenWhiteList: string | null;',
    '}>;',
    '',
    'export const ADMIN_CONTRACT_ADDRESSES_BY_CHAIN_ID: AdminContractAddressesByChainId = {',
  ];

  const seenChainIds = new Set<number>();
  if (parsed.hardhat && !parsed.localhost) {
    parsed.localhost = parsed.hardhat;
  }
  for (const [network, chainId] of Object.entries(NETWORK_CHAIN_IDS)) {
    if (seenChainIds.has(chainId)) continue;
    const networkContracts = parsed[network];
    if (!networkContracts) continue;
    seenChainIds.add(chainId);
    const addrs = buildAdminContractAddresses(networkContracts);
    lines.push(`  ${chainId}: {`);
    for (const [k, v] of Object.entries(addrs)) {
      const val = v === null ? 'null' : `'${v}'`;
      lines.push(`    ${k}: ${val},`);
    }
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  const outPath = path.join(OUTPUT_ROOT, 'configs', 'admin-contract-addresses.generated.ts');
  ensureDir(path.dirname(outPath));
  fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
  console.log('Wrote', path.relative(CONTRACTS_ROOT, outPath));
}

type AbiExportStyle = 'const_as_const' | 'default_export';

const ABI_MAPPINGS: Array<{
  artifact: string;
  outPath: string;
  exportName: string;
  style: AbiExportStyle;
}> = [
    { artifact: 'TokenWhiteList.json', outPath: 'configs/abis/tokenWhitelist.ts', exportName: 'TokenWhitelistAbi', style: 'const_as_const' },
    { artifact: 'PremiumRegistry_Implementation.json', outPath: 'configs/abis/premiumRegistry.ts', exportName: 'PremiumRegistryABI', style: 'default_export' },
    { artifact: 'PremiumSetting_Implementation.json', outPath: 'configs/abis/premiumSetting.ts', exportName: 'PremiumSettingABI', style: 'default_export' },
    { artifact: 'TimeLockRouter_Implementation.json', outPath: 'configs/abis/timelockAbi.ts', exportName: 'TimelockABI', style: 'default_export' },
    { artifact: 'EIP712LegacyVerifier_Implementation.json', outPath: 'configs/abis/legacyAgreement.ts', exportName: 'LegacyAgreementAbi', style: 'default_export' },
    { artifact: 'TimelockERC20_Implementation.json', outPath: 'constants/erc20TimelockAbi.ts', exportName: 'erc20TimelockAbi', style: 'const_as_const' },
    { artifact: 'TimelockERC721_Implementation.json', outPath: 'constants/erc721TimelockAbi.ts', exportName: 'erc721TimelockAbi', style: 'const_as_const' },
    { artifact: 'TimelockERC1155_Implementation.json', outPath: 'constants/erc1155TimelockAbi.ts', exportName: 'erc1155TimelockAbi', style: 'const_as_const' },
    { artifact: 'MultisigLegacyRouter_Implementation.json', outPath: 'configs/abis/legacyAbi.ts', exportName: 'LegacyAbi', style: 'default_export' },
    { artifact: 'TransferLegacyRouter_Implementation.json', outPath: 'configs/abis/legacyRouterAbi.ts', exportName: 'LegacyRouterAbi', style: 'default_export' },
  ];

function writeAbiFile(
  network: string,
  artifactName: string,
  outRelPath: string,
  exportName: string,
  style: AbiExportStyle
): void {
  const deploymentsNetwork = path.join(DEPLOYMENTS_DIR, network);
  const artifactPath = path.join(deploymentsNetwork, artifactName);
  if (!fs.existsSync(artifactPath)) {
    console.warn('Missing artifact, skipping:', artifactName);
    return;
  }
  const content = fs.readFileSync(artifactPath, 'utf-8');
  let abi: unknown;
  try {
    const parsed = JSON.parse(content);
    abi = parsed.abi;
  } catch {
    console.warn('Invalid JSON or missing abi:', artifactName);
    return;
  }
  if (!Array.isArray(abi)) {
    console.warn('abi is not an array:', artifactName);
    return;
  }

  const abiJson = JSON.stringify(abi, null, 2);
  let body: string;
  if (style === 'const_as_const') {
    body = `export const ${exportName} = ${abiJson} as const;\n`;
  } else {
    body = `const ${exportName} = ${abiJson};\n\nexport default ${exportName};\n`;
  }

  const outPath = path.join(OUTPUT_ROOT, outRelPath);
  ensureDir(path.dirname(outPath));
  fs.writeFileSync(outPath, body, 'utf-8');
  console.log('Wrote', path.relative(CONTRACTS_ROOT, outPath));
}

function writeAbis(): void {
  const data = fs.readFileSync(CONTRACT_ADDRESSES_PATH, 'utf-8');
  const parsed = JSON.parse(data) as ContractAddressesJson;
  const networks = Object.keys(parsed).filter((n) => NETWORK_CHAIN_IDS[n] !== undefined);
  const deploymentDirs = networks.filter((n) => fs.existsSync(path.join(DEPLOYMENTS_DIR, n)));
  const allDirs =
    fs.existsSync(DEPLOYMENTS_DIR) ?
      fs.readdirSync(DEPLOYMENTS_DIR).filter((name) => {
        const p = path.join(DEPLOYMENTS_DIR, name);
        return fs.statSync(p).isDirectory() && !name.startsWith('.');
      }) :
      [];
  const network = deploymentDirs[0] ?? allDirs[0] ?? networks[0] ?? 'sepolia';
  for (const m of ABI_MAPPINGS) {
    writeAbiFile(network, m.artifact, m.outPath, m.exportName, m.style);
  }
}

function writeSubgraphNetworks(): void {
  const data = fs.readFileSync(CONTRACT_ADDRESSES_PATH, 'utf-8');
  const parsed = JSON.parse(data) as ContractAddressesJson;
  const output: SubgraphNetworksOutput = {};
  for (const [network, contracts] of Object.entries(parsed)) {
    if (network === 'hardhat' && output['localhost']) continue;
    const outputKey = network === 'hardhat' ? 'localhost' : network;
    const entries: Record<string, { address: string; startBlock?: number }> = {};
    for (const [contractName, entry] of Object.entries(contracts)) {
      const addr = checksum(entry?.address);
      if (!addr) continue;
      const startBlock = getStartBlock(network, contractName);
      entries[contractName] = startBlock !== undefined ? { address: addr, startBlock } : { address: addr };
    }
    if (Object.keys(entries).length > 0) output[outputKey] = entries;
  }
  const outPath = path.join(OUTPUT_ROOT, 'subgraph-networks.json');
  fs.writeFileSync(outPath, JSON.stringify(output, null, 2), 'utf-8');
  console.log('Wrote', path.relative(CONTRACTS_ROOT, outPath));
}

function printCopyInstructions(): void {
  const subgraphPath = path.join(OUTPUT_ROOT, 'subgraph-networks.json');
  console.log('');
  console.log('--- Copy instructions ---');
  console.log('');
  console.log('UI: Copy output/sync-ui/* into the UI repo src/ so that:');
  console.log('     output/sync-ui/configs/  →  computing/src/configs/');
  console.log('     output/sync-ui/constants/  →  computing/src/constants/');
  console.log('');
  console.log('Admin: Copy output/sync-ui/configs/admin-contract-addresses.generated.ts to');
  console.log('       computing-admin/src/configs/contract-addresses.generated.ts');
  console.log('');
  console.log('Subgraph: Merge addresses from output/sync-ui/subgraph-networks.json into the');
  console.log('     subgraph networks file. For each network (e.g. sepolia), replace or merge');
  console.log('     that key in 10102-subgraph/networks.json with the corresponding object');
  console.log('     from subgraph-networks.json. Then run "yarn build:sepolia" and');
  console.log('     "yarn deploy:sepolia" in the subgraph repo to redeploy the indexer.');
  console.log('');
}

function main(): void {
  if (!fs.existsSync(CONTRACT_ADDRESSES_PATH)) {
    console.error('contract-addresses.json not found at', CONTRACT_ADDRESSES_PATH);
    process.exit(1);
  }
  ensureDir(OUTPUT_ROOT);
  writeAddresses();
  writeAdminAddresses();
  writeAbis();
  writeSubgraphNetworks();
  printCopyInstructions();
}

main();
